Apps/auction/urls.py
from django.conf.urls import url


from . import views

app_name='auction'

urlpatterns = (
	url(r'^$', views.auction_list, name='index_view'),
	url(r'^auctions/$', views.auction_list, name='auction_list'),
	url(r'^auctions/detail/(?P<pk>\d+)/$', views.auction_detail, name='auction_detail'),
	url(r'^auctions/detail/(?P<pk>\d+)/edit/$', views.edit_auction, name='edit_auction'),
	url(r'^auctions/detail/(?P<pk>\d+)/delete/$', views.delete_auction, name='delete_auction'),
	url(r'^auctions/detail/(?P<pk>\d+)/bid/$',views.bid_on_auction, name='bid_on_auction'),
	url(r'^auctions/detail/(?P<pk>\d+)/bid/list/$', views.get_list_of_bids),
	url(r'^auctions/(?P<user>\w+)/auctions-list/$',views.auction_list_by_user, name='profile_auction_list'),
	url(r'^auctions/search/$', views.search_view, name='search_auction'),
	url(r'^auctions/create/$', views.create_auction, name='create_auction'),
	url(r'^auctions/create/confirm/$', views.confirm_auction, name='confirm_auction'),

	



	)

YAAS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'^yaas/', include("Apps.auction.urls")),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include("Apps.account.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/auction/models.py
from __future__ import unicode_literals
from django.dispatch import receiver
from django.db.models.signals import post_save

from datetime import datetime, timedelta
from django.db import models
from django.contrib.auth.models import User
from django.core.mail import send_mail

# Create your models here.
AUCTION_STATUS = (
	('Act', 'Active'),
	('Ban', 'Banned'),
	('Due', 'Due'),
	('Fin', 'Adjundicated')
	)



def get_deadline():
	return datetime.today() + timedelta(hours=24) 

class Auction(models.Model):
	'''Model for auction product/item'''
	seller = models.ForeignKey(User)
	title = models.CharField(max_length=120)
	description = models.TextField()
	start_price = models.PositiveIntegerField()
	created_at = models.DateTimeField(auto_now_add= True)
	deadline = models.DateTimeField(default= get_deadline)
	status = models.CharField(max_length=3, choices=AUCTION_STATUS, default='Act')

	def save(self, *args, **kwargs):
		if not self.start_price:
			self.start_price = self.minimum_price
		super(Auction, self).save(*args, **kwargs)

	def __str__(self):
		return self.title


@receiver(post_save, sender=Auction)
def send_confirmation_email(sender, *args, **kwargs):
	'''sends an email to the user notifying that the auction has been created'''
	if kwargs.get('created', False):
		# send_mail('Subject',
		# 	'Message Body',
		# 	'pythonkhata@gmail.com',
		# 	[kwargs['instance'].seller.email],
		# 	fail_silently = False

		# 	)
		print 'email sent '



class Bid(models.Model):
	bidder = models.ForeignKey(User, on_delete=models.CASCADE)
	product = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='product')
	#amount_before_bid = models.PositiveIntegerField()
	increase_by = models.PositiveIntegerField()
	amount_after_bid = models.PositiveIntegerField()
	bid_time = models.DateTimeField(auto_now=True)

	

	def __str__(self):
		return self.bidder.username

		




	

Apps/auction/forms.py
from django import forms
from .models import Auction, Bid


class AuctionForm(forms.ModelForm):
	class Meta:
		model = Auction
		seller = Auction.seller
		deadline = forms.DateTimeField()
		fields = ('title', 'description', 'start_price','deadline')
		widgets = {
			'title': forms.TextInput(attrs={'class':'form-control'}),
			'description' : forms.Textarea(attrs= {'class' : 'form-control'}),
			'start_price' : forms.NumberInput(attrs= {'class' : 'form-control'}),
			'deadline' : forms.DateTimeInput(attrs= {'class' : 'form-control'})
		}
		

class BidForm(forms.ModelForm):
	class Meta:
		model = Bid
		fields = ('increase_by',)

Apps/auction/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.urls import reverse
from .forms import AuctionForm, BidForm

from django.contrib.auth.decorators import login_required


from .models import Auction, Bid

# Create your views here.


def index_view(request):
	return render(request, 'auction/index.html')



def auction_list(request):
	auctions = Auction.objects.all()
	return render(request, 'auction/auction_list.html', {'auction_list':auctions})


def auction_list_by_user(request, user):
	'''Returns all the lists of auctions by filtered user'''
	auctions = get_list_or_404(Auction, seller__username=user)
	return render(request, 'auction/auction_list_user.html', {'auctions':auctions})



def auction_detail(request, pk):
	'''Gets the detail of auction instance where the primary key matches with the passed pk'''
	auction = get_object_or_404(Auction, pk=pk)
	latest_high_bid_amount = get_current_bid_amount(request,pk)

	return render(request, 'auction/auction_detail.html', {'auction':auction, 'current_price':latest_high_bid_amount })



def create_auction(request):
	'''Display the form to create an auction instance and send the form to confirm_auction()
		where it asks for confirmation to whether save it or not'''
	errors = ''
	if request.method == 'GET':
		form = AuctionForm()
	elif request.method == 'POST':
		form = AuctionForm(request.POST)
		if form.is_valid():
			return render(request, 'auction/confirmation_form.html', {'form':form})
		else:
			errors = form.errors
	return render(request, 'auction/create_auction.html', {'form':form, 'errors':errors})


def delete_auction(request,pk):
	'''Deletes the selected auction instnce'''
	try:
		auction = Auction.objects.get(pk=pk)
	except Auction.DoesNotExist:
		print 'The item you asked for doesnt exist'
	auction.delete()
	messages.add_message(request, messages.SUCCESS, 'Successfully deleted auction item')
	return HttpResponseRedirect(reverse('auction:auction_list'))


def confirm_auction(request):
	'''Get the passed post data from create_auction() and re-desplay the form with filled data
		and save it if confirm_submit is in POST data which is passed thru form'''
	if request.method == 'POST' and 'confirm_submit' in request.POST:
		form = AuctionForm(request.POST)
		if form.is_valid():
			unconfirmed_form = form.save(commit=False)
			unconfirmed_form.seller = request.user
			unconfirmed_form.save()
			messages.add_message(request, messages.SUCCESS, 'Successfully created new auction')
			return HttpResponseRedirect(reverse('auction:auction_list'))
		else:
			print form.errors
	return auction_list(request)


def edit_auction(request,pk):
	'''Edit the auction instance that a user belongs to'''
	auction = Auction.objects.get(pk=pk, seller=request.user)
	submitted_auction_form = AuctionForm(instance=auction)
	if request.method == 'POST':
		submitted_auction_form = AuctionForm(request.POST, instance=auction)
		if submitted_auction_form.is_valid():
			submitted_auction_form.save()
			messages.add_message(request, messages.SUCCESS, 'Your auction item is updated')
			return HttpResponseRedirect(reverse('auction:auction_list'))
		else:
			errors = submitted_auction_form.errors
	return render(request, 'auction/edit_auction.html', {'form':submitted_auction_form}) 


def get_current_bid_amount(request,pk):
	'''Returns the current highest bid amount related to auction instance
		Using backward relation lookup; that related_name = product. First see if bid
		instance exists. If yes, get the latest bid instance related to this auction 
		instance else get the initial amount'''
	auction = get_object_or_404(Auction, pk=pk)
	if auction.product.exists():
		latest_high_bid_amount = auction.product.latest('pk').amount_after_bid
	else:
		latest_high_bid_amount = auction.start_price
	return latest_high_bid_amount




def bid_on_auction(request,pk):
	'''Get a POST data of bid amount (increased_by) and increase the value by adding that to 
		latest highest bid amount and thus save the model instance'''
	product = Auction.objects.get(pk=pk)
	latest_high_bid_amount = get_current_bid_amount(request,pk)
	if request.method == 'GET':
		form = BidForm()
	if request.user == product.seller:
		return render(request, 'auction/404.html', {'message': 'You cannot bid on your own auction'})

	if request.method == 'POST':
		form = BidForm(request.POST)
		if form.is_valid():
			unconfirmed_form = form.save(commit=False)
			unconfirmed_form.product = product
			unconfirmed_form.bidder = request.user
			increase_by = request.POST['increase_by']
			unconfirmed_form.increase_by = increase_by
			unconfirmed_form.amount_after_bid = int(increase_by) + latest_high_bid_amount
			unconfirmed_form.save()
			messages.add_message(request,messages.SUCCESS, 'You have successfully bidded on %s' %product.title)
			return HttpResponseRedirect(reverse('auction:auction_list'))
		else:
			errors = form.errors
	return render(request, 'auction/bid_form.html', {'form':form, 'product':product, 'current_amount':latest_high_bid_amount})


def get_list_of_bids(request,pk):
	bids = Bid.objects.filter(bidder=request.user, product=pk)
	for b in bids:
		print b.amount_after_bid
	return HttpResponse('H')





def search_view(request):
	'''Gets the seearch words and display the matching results'''
	#I should try it via ajax
	searchwords = request.GET['srch-term']
	#print 'The input words were' ,searchwords
	search_results = Auction.objects.filter(title__icontains=searchwords)
	
	#return HttpResponse(search_results)
	messages.add_message(request, messages.SUCCESS, 'Your search for %s yielded following results' %searchwords)
	return render(request,'auction/search_results.html', {'results':search_results})

templates/auction/auction_detail.html
{% extends 'base.html' %}

{% block content_block %}
	
		<h3>Seller: {{auction.seller}}</h3>
		<div class="row">
			<div id="description" class="col-md-4">
				<p> <strong>{{auction.title}}</strong></p>
				<p>
					{{auction.description}}
				</p>
			</div>
		</div>

		<div class="row">
			<div id="deadline" class="col-md-4">
				<p> This auction ends at {{auction.deadline}}</p>
			</div>
		</div>

		<div class="row">
			<div id="price" class="col-md-4">
				<p> Auction started at: {{auction.start_price}} euros.</p>
				<p>Current amount : {{current_price}} euros.</p>
				<a href="{% url 'auction:bid_on_auction' auction.pk %}">
					<button class="btn btn-info" type="button">
						Bid
					</button>
				</a>
				
			</div>
		</div>



	
{% endblock %}

templates/auction/auction_list.html
{% extends 'base.html' %}

{% block content_block %}
	{% if messages %}
		{% for message in messages %}
			<h2 style="color:green"> {{message}}</h2>
		{% endfor %}
	{% endif %}
	
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Product</th>
				<th> Seller </th>
				<th>Start Price</th>
				<th>Status </th>
			</tr>
		</thead>

		<tbody>
		
		{% for auction in auction_list %}
			<tr>
				<td><a href="{% url 'auction:auction_detail' auction.pk %}"> {{auction.title}}</a></td>
				<td>{{auction.seller}}</td>
				<td>{{auction.start_price}} Euros</td>
				<td>{{auction.get_status_display}}</td><!--Display whole ACTIVE instead of ACT -->
			</tr></a>
		{% endfor %}

		</tbody>
		
	</table>
	
{% endblock %}

templates/auction/auction_list_user.html
{% extends 'base.html' %}

{% block content_block %}
	<ul class="list-group">
		{% for auction in auctions %}
			<li class="list-group-item">{{auction.title}}
				
					<span class="badge">
						<a href="{% url 'auction:edit_auction' auction.pk %}" style="color:white"> Edit <span class="glyphicon glyphicon-edit"></span> 
						</a>
					</span>
					
					<span class="badge"> 
						<a href="{% url 'auction:delete_auction' auction.pk %}" style="color:white"> Delete <span class="glyphicon glyphicon-remove"> </span>
						</a>
					</span>
				
			</li>
		
		{% endfor %}
	</ul>
{% endblock %}

templates/auction/bid_form.html
{% extends 'base.html' %}

{% block content_block %}
<h2> {{product}} </h2>
Current amount is: {{current_amount}}
<form method='POST' action=''>
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" name="bid" value="Bid">
</form>
{% endblock %}

templates/auction/confirmation_form.html
{% extends 'base.html' %}

{% block content_block %}
<h2 style="color:green"> Please confirm your data. </h2>
	<form class="form-horizontal" method="POST" action="{% url 'auction:confirm_auction' %}">
	{% csrf_token %}
	<div class="form-group">
			<label class="control-label"> Title: </label>
			{{form.title}} 
		</div>

		<div class="form-group">
			Description: {{form.description}}
		</div>

		<div class="form-group">
			Price: {{form.start_price}}
		</div>

		<div class="form-group">
			Deadline: {{form.deadline}}
		</div>

		<div class="form-group">
			<input type="submit" name="confirm_submit" value="Yes, create an auction">
			<input type="submit" name="reject_confirm" value="Cancel, creating auction">
		</div>
	</form>

{% endblock %}

templates/auction/create_auction.html
{% extends 'base.html' %}

{% block content_block %}
{% if errors %}

	<div id="errors">
		<p> {{errors}}</p>
		
	</div>
	{% endif %}
	
		<form  method="POST" action="">
		{% csrf_token %}
		<div class="form-group">
			<label class="control-label"> Title: </label>
			{{form.title}}
		</div>

		<div class="form-group">
			Description: {{form.description}}
		</div>

		<div class="form-group">
			Price: {{form.start_price}}
		</div>

		<div class="form-group">
			Deadline: {{form.deadline}}
		</div>

		<div class="form-group">
			<input type="submit" value="Create Auction">
		</div>
		</form>

					
	
{% endblock %}

templates/auction/edit_auction.html
{% extends 'base.html' %}

{% block content_block %}

	<h2>Edit the auction </h2>
	<form class="form-group" method="POST" action="">
	{% csrf_token %}
		{{form}}
		<br>
		<input class="form-control" type="submit" name="submit" value="Update Auction" style="background-color:lightblue">
	</form>
{% endblock %}

templates/auction/index.html
{% extends "base.html" %}

templates/auction/search_results.html
{% extends 'base.html' %}

{% block content_block %}
	{% if messages %}
		{% for message in messages %}
			<h2 style="color:green"> {{message}}</h2>
		{% endfor %}
	{% endif %}
	
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Product</th>
				<th> Seller </th>
				<th>Start Price</th>
				<th>Status </th>
			</tr>
		</thead>

		<tbody>
		
		{% for auction in results %}
			<tr>
				<td><a href="{% url 'auction:auction_detail' auction.pk %}"> {{auction.title}}</a></td>
				<td>{{auction.seller}}</td>
				<td>{{auction.start_price}} Euros</td>
				<td>{{auction.get_status_display}}</td><!--Display whole ACTIVE instead of ACT -->
			</tr></a>
		{% endfor %}

		</tbody>
		
	</table>
	
{% endblock %}