Apps/account/urls.py
from django.conf.urls import url


from .views import (
	user_registration,
	user_login,
	user_profile_change,
	user_logout,
	get_user_profile


	)

app_name = 'account'
urlpatterns = [

	url(r'^register/$', user_registration, name='user_register'),
	url(r'^login/$', user_login, name='user_login'),
	url(r'^profile/user/$', get_user_profile, name='user_profile'),
	url(r'^edit/$', user_profile_change, name='edit_profile'),
	url(r'^logout/$', user_logout, name='user_logout'),
]

Apps/auction/urls.py
from django.conf.urls import url


from . import views

app_name='auction'

urlpatterns = (
	url(r'^$', views.auction_list, name='index_view'),
	url(r'^auctions/$', views.auction_list, name='auction_list'),
	url(r'^auctions/detail/(?P<pk>\d+)/$', views.auction_detail, name='auction_detail'),
	url(r'^auctions/detail/(?P<pk>\d+)/edit/$', views.edit_auction, name='edit_auction'),
	url(r'^auctions/detail/(?P<pk>\d+)/delete/$', views.delete_auction, name='delete_auction'),
	url(r'^auctions/detail/(?P<pk>\d+)/bid/$',views.bid_on_auction, name='bid_on_auction'),
	url(r'^auctions/detail/(?P<pk>\d+)/bid/list/$', views.get_list_of_bids),
	url(r'^auctions/(?P<user>\w+)/auctions-list/$',views.auction_list_by_user, name='profile_auction_list'),
	url(r'^auctions/search/$', views.search_view, name='search_auction'),
	url(r'^auctions/create/$', views.create_auction, name='create_auction'),
	url(r'^auctions/create/confirm/$', views.confirm_auction, name='confirm_auction'),

	



	)

YAAS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'^yaas/', include("Apps.auction.urls")),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include("Apps.account.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">  
{% load static %}
	<head>

	<!--All the bootstrap and js mcdn here -->
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<!--end of bootstrap and js import -->
	<!--Custom js and css files here-->
	<script src="{% static 'auction/myajax.js' %}"></script>




		{% block title %} <title>YAAS</title>{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand" href="{% url 'auction:index_view' %}">YAAS</a>
				</div>
				<ul class="nav navbar-nav navbar-right">
					<li>
						<form class="navbar-form" role="search" action="{% url 'auction:search_auction' %}">
        					<div class="input-group">
            					<input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
           					 <div class="input-group-btn">
                				<button class="btn btn-default" type="submit" id="srch-button"><i class="glyphicon glyphicon-search"></i></button>
            				</div>
       						 </div>
       					 </form>
       				</li>

					{% if not user.is_authenticated %}
						<li> <a href="{% url 'account:user_register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
						<li><a href="{% url 'account:user_login' %}"><span class="glyphicon glyphicon-log-in"> </span> Login</a></li>
					{% else %}
					<li><a href="{% url 'auction:create_auction' %}"><span class="glyphicon glyphicon-upload"></span> Crete Auction</a></li>
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" href=""> {{request.user}}<span class="caret"></span></a>
							
							<ul class="dropdown-menu">
								<li><a href="{% url 'account:user_profile' %}"> <span class="glyphicon glyphicon-user"></span> My profile</a></li>
								<li><a href=""><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
								<li><a href="{% url 'account:user_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
							</ul>
						</li>
					{% endif %}

				</ul>
			</div>
		</nav>

		<div class="jumbotron text-center">
			<h2> Buy and Sell with ease</h2>
		</div>

		<!--All the contents goes here -->
		<div class="container">
			{% block content_block %}
				
			{% endblock %}
		</div>
		



		

	</body>
</html>